# Generated by Django 4.0.3 on 2022-06-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note_contact_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
